2021/01/08 18:23:25 Attempt 1 of http call to http://10.0.0.8:16384/sendlogstoartifacts/info
2021/01/08 18:23:25 Attempt 1 of http call to http://10.0.0.8:16384/sendlogstoartifacts/status
[2021-01-08T18:23:27.171016] Entering context manager injector.
[context_manager_injector.py] Command line Options: Namespace(inject=['ProjectPythonPath:context_managers.ProjectPythonPath', 'RunHistory:context_managers.RunHistory', 'TrackUserError:context_managers.TrackUserError'], invocation=['train.py', '--C', '0.6', '--max_iter', '20'])
Script type = None
Starting the daemon thread to refresh tokens in background for process with pid = 103
Entering Run History Context Manager.
[2021-01-08T18:23:29.819424] Current directory: /mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-133986/azureml/hd_528d7c91-b54a-4d3d-87ac-943dad6df73a_2/mounts/workspaceblobstore/azureml/HD_528d7c91-b54a-4d3d-87ac-943dad6df73a_2
[2021-01-08T18:23:29.819579] Preparing to call script [train.py] with arguments:['--C', '0.6', '--max_iter', '20']
[2021-01-08T18:23:29.819637] After variable expansion, calling script [train.py] with arguments:['--C', '0.6', '--max_iter', '20']

Performing interactive authentication. Please follow the instructions on the terminal.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FGAJMWCZN to authenticate.
Starting the daemon thread to refresh tokens in background for process with pid = 103


[2021-01-08T18:38:49.566396] The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 900.0 seconds
1 items cleaning up...
Cleanup took 0.06418418884277344 seconds
Traceback (most recent call last):
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/azureml/_base_sdk_common/common.py", line 579, in perform_interactive_login
    use_cert_sn_issuer=use_cert_sn_issuer)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/azureml/_vendor/azure_cli_core/_profile.py", line 228, in find_subscriptions_on_login
    tenant, self._ad_resource_uri)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/azureml/_vendor/azure_cli_core/_profile.py", line 786, in find_through_interactive_flow
    token_entry = context.acquire_token_with_device_code(resource, code, _CLIENT_ID)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/adal/authentication_context.py", line 311, in acquire_token_with_device_code
    return self._acquire_token(token_func, user_code_info.get('correlation_id', None))
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/adal/authentication_context.py", line 304, in token_func
    token = token_request.get_token_with_device_code(user_code_info)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/adal/token_request.py", line 394, in get_token_with_device_code
    token = client.get_token_with_polling(oauth_parameters, interval, expires_in)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/adal/oauth2_client.py", line 362, in get_token_with_polling
    wire_response)
adal.adal_error.AdalError: Unexpected polling state code_expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-133986/azureml/hd_528d7c91-b54a-4d3d-87ac-943dad6df73a_2/mounts/workspaceblobstore/azureml/HD_528d7c91-b54a-4d3d-87ac-943dad6df73a_2/azureml-setup/context_manager_injector.py", line 201, in execute_with_context
    runpy.run_path(sys.argv[0], globals(), run_name="__main__")
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "train.py", line 15, in <module>
    ws = Workspace.get("quick-starts-ws-133986")
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/azureml/core/workspace.py", line 559, in get
    auth = InteractiveLoginAuthentication()
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/azureml/core/authentication.py", line 462, in __init__
    perform_interactive_login(tenant=tenant_id, cloud_type=self._cloud_type)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/azureml/_base_sdk_common/common.py", line 589, in perform_interactive_login
    raise AuthenticationException('Unknown error occurred during authentication. Error detail: ' + str(err))
azureml.exceptions._azureml_exception.AuthenticationException: AuthenticationException:
	Message: Unknown error occurred during authentication. Error detail: Unexpected polling state code_expired
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "Authentication"
        },
        "message": "Unknown error occurred during authentication. Error detail: Unexpected polling state code_expired"
    }
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 15, in <module>
    ws = Workspace.get("quick-starts-ws-133986")
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/azureml/core/workspace.py", line 559, in get
    auth = InteractiveLoginAuthentication()
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/azureml/core/authentication.py", line 462, in __init__
    perform_interactive_login(tenant=tenant_id, cloud_type=self._cloud_type)
  File "/azureml-envs/azureml_ba9520bf386d662001eeb9523395794e/lib/python3.6/site-packages/azureml/_base_sdk_common/common.py", line 589, in perform_interactive_login
    raise AuthenticationException('Unknown error occurred during authentication. Error detail: ' + str(err))
UserScriptException: UserScriptException:
	Message: Unknown error occurred during authentication. Error detail: Unexpected polling state code_expired
	InnerException AuthenticationException:
	Message: Unknown error occurred during authentication. Error detail: Unexpected polling state code_expired
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "Authentication"
        },
        "message": "Unknown error occurred during authentication. Error detail: Unexpected polling state code_expired"
    }
}
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Unknown error occurred during authentication. Error detail: Unexpected polling state code_expired"
    }
}

[2021-01-08T18:38:49.807095] Finished context manager injector with Exception.
2021/01/08 18:38:50 Failed to parse control script error: /mnt/batch/tasks/workitems/5e13eb79-3926-44c8-9f06-5138747f4b89/job-1/hd_528d7c91-b54a-4d3_17071c03-77dd-47bd-8cbf-a7bc5e83eef5/wd/runTaskLetTask_error.json to json File /mnt/batch/tasks/workitems/5e13eb79-3926-44c8-9f06-5138747f4b89/job-1/hd_528d7c91-b54a-4d3_17071c03-77dd-47bd-8cbf-a7bc5e83eef5/wd/runTaskLetTask_error.json doesn't exist
2021/01/08 18:38:50 Failed to run the wrapper cmd with err: exit status 1
2021/01/08 18:38:50 Attempt 1 of http call to http://10.0.0.8:16384/sendlogstoartifacts/status
2021/01/08 18:38:50 mpirun version string: {
Intel(R) MPI Library for Linux* OS, Version 2018 Update 3 Build 20180411 (id: 18329)
Copyright 2003-2018 Intel Corporation.
}
2021/01/08 18:38:50 MPI publisher: intel ; version: 2018
2021/01/08 18:38:50 Process Exiting with Code:  1
